title: Xiangzhe Yuan's Homepage
page-top-title: Xiangzhe Yuan
top-section-bg-text: Human Computer Interaction
home-subtitle: Xiangzhe Yuan&ensp;|&ensp;袁湘哲
copyright-text: '&copy; Xiangzhe Yuan 2023-2024. All Rights Reserved.'
